---------------------TABELE
drop table log_erori;
create table log_erori (
    id_log number generated by default as identity primary key,
    nr_exercitiu number,
    mesaj varchar2(4000),
    data_eroare timestamp
);

select * from ldd_audit;
drop table lmd_audit;
create table lmd_audit (
    id_log number generated by default as identity primary key,
    nr_exercitiu number,
    nume_tabela varchar2(50),
    mesaj varchar2(4000),
    data_inregistrare timestamp
);

drop table ldd_audit;
create table ldd_audit (
    id_audit number generated by default as identity primary key,
    nr_exercitiu number,
    nume_utilizator varchar2(50),
    tip_ldd varchar2(50),
    tabela varchar2(100),
    data_inregistrare timestamp default systimestamp
);

select * from autor;
drop table autor;
CREATE TABLE autor
(   cod_autor varchar2(10) constraint pk_autor primary key,
    nume_autor varchar2(50) not null,
    prenume_autor varchar2(50) not null,
    nume_companie varchar2(50));


drop table editura;
select * from editura;
CREATE TABLE editura
(   cod_editura number(4) constraint pk_editura primary key,
    nume_editura varchar2(50) not null,
    oras_editura varchar2(50) not null,
    data_infiintare date not null);


drop table gen;
select * from gen;
CREATE TABLE gen
(   cod_gen number(3) constraint pk_gen primary key,
    nume_gen varchar(20) not null,
    subgen varchar(20) default null);
    
    
drop table librarie;
select * from librarie;
CREATE TABLE librarie
(   cod_librarie varchar2(5) constraint pk_librarie primary key,
    nume_librarie varchar2(50) not null,
    oras_librarie varchar2(50) not null,
    website_librarie varchar2(50) default null);
   
   
drop table carte;
select * from carte;
CREATE TABLE carte
(   cod_carte number(6) constraint pk_carte primary key,
    nume_carte varchar2(50) not null,
    cod_autor varchar2(10) not null,
    constraint fk_autor foreign key (cod_autor) references 
AUTOR(cod_autor),
    cod_editura number(4) not null,
    constraint fk_editura foreign key (cod_editura) references 
EDITURA(cod_editura),
    cod_gen number(3) not null,
    constraint fk_gen foreign key (cod_gen) references 
GEN(cod_gen),
    cod_librarie varchar2(5) not null,
    constraint fk_librarie foreign key (cod_librarie) references 
LIBRARIE(cod_librarie),
    numar_pagini number not null,
    limba varchar2(20) not null,
    data_publicare date not null,
    pret_carte number not null);
    
    
select * from metoda_livrare;
CREATE TABLE metoda_livrare
(   cod_livrare number(5) constraint pk_livrare primary key,
    nume_livrare varchar2(10) default 'terestru' 
constraint chk_nume_livrare check ( lower(nume_livrare) in
('terestru','maritim','oceanic','aerian')),
    firma_transport varchar2(50) not null,
    cost_livrare number not null);


select * from status_comanda;
CREATE TABLE status_comanda
(   cod_status number constraint pk_status_comanda primary key,
    nume_status_comanda varchar2(20) default 'in curs de procesare'
constraint chk_nume_status_comanda check (lower(nume_status_comanda) in ( 'in curs de procesare', 'procesata', 
'in curs de pregatire', 'in depozit', 'la curier', 'finalizata')));

select * from strada;
CREATE TABLE strada
(   cod_strada number(2) constraint pk_strada primary key,
    nume_strada varchar2(50) not null,
    numar_strada number not null);


drop table oras;
select * from oras;
CREATE TABLE oras
(   cod_oras number constraint pk_oras primary key,
    nume_oras varchar2(50) not null,
    cod_strada number(2)not null,
    constraint fk_strada foreign key (cod_strada) references
STRADA(cod_strada));

select * from client;
CREATE TABLE client
(   id_client number(6) constraint pk_client primary key,
    nume_client varchar2(50) not null,
    prenume_client varchar2(50) not null,
    email_client varchar2(50) default null,
    numar_telefon_client varchar2(10) default null,
    data_inregistrare date default sysdate);
    

drop table recenzie;
select * from recenzie;
CREATE TABLE recenzie 
(   cod_recenzie number not null,
    id_client number not null,
    cod_carte number not null,
    constraint pk_recenzie primary key (cod_recenzie),
    constraint fk_recenzie_client foreign key (id_client) 
references CLIENT(id_client),
    constraint fk_recenzie_carte foreign key (cod_carte) 
references CARTE(cod_carte),
    descriere varchar2(250),
    nota number(2, 1) not null,
    constraint chk_nota check (nota between 0 and 10));
  
alter table recenzie
add constraint unq_recenzie unique (cod_recenzie,id_client,cod_carte,descriere,nota);
    


drop table adresa;
select * from adresa;
CREATE TABLE adresa
(   cod_adresa number(5) constraint pk_adresa primary key,
    cod_oras number not null,
    constraint fk_adresa_oras foreign key (cod_oras)
references ORAS(cod_oras));


drop table comanda;
select * from comanda;
CREATE TABLE comanda
(   cod_comanda number(4) constraint pk_comanda primary key,
    pret_total number(10),
    cod_adresa number(5)not null,
    constraint fk_comanda_adresa foreign key (cod_adresa) 
references ADRESA(cod_adresa),
    cod_status number not null,
    constraint fk_comanda_status foreign key (cod_status)
references STATUS_COMANDA(cod_status),
    cod_livrare number(5) not null,
    constraint fk_comanda_livrare foreign key (cod_livrare)
references METODA_LIVRARE(cod_livrare),
    data_plasare_comanda date default sysdate,
    finalizare_comanda date default null);
    

select * from adresa_client;
CREATE TABLE adresa_client
(   cod_adresa_client number(5) constraint pk_adresa_client primary key,
    cod_adresa number(5) not null,
    constraint fk_ac_adresa foreign key (cod_adresa) 
references ADRESA(cod_adresa),
    id_client number(6) not null,
    constraint fk_ac_client foreign key (id_client) 
references CLIENT(id_client));

alter table adresa_client
add constraint unq_adresa_client unique (cod_adresa, id_client);

select * from carte_comanda;
drop table carte_comanda;
CREATE TABLE carte_comanda
(   cod_carte_comanda number(5) constraint pk_carte_comanda primary key,
    cod_comanda number(4) not null,
    constraint fk_cc_comanda foreign key (cod_comanda) 
references COMANDA(cod_comanda),
    cod_carte number(6) not null,
    constraint fk_cc_carte foreign key (cod_carte) 
references CARTE(cod_carte));

alter table carte_comanda
add constraint unq_carte_comanda unique (cod_comanda,cod_carte);



drop table detalii_comanda;
select * from detalii_comanda;
CREATE TABLE detalii_comanda
(   cod_detalii_comanda number(5) constraint pk_detalii_comanda primary key,
    id_client number(6) not null,
    constraint fk_dc_client foreign key (id_client) 
references CLIENT(id_client),
    cod_librarie varchar2(5) not null,
    constraint fk_ac_librarie foreign key (cod_librarie) 
references LIBRARIE(cod_librarie),
    cod_comanda number(4) not null,
    constraint fk_dc_comanda foreign key (cod_comanda) 
references COMANDA(cod_comanda));

alter table detalii_comanda
add constraint unq_detalii_comanda unique (cod_comanda, id_client, cod_librarie);

    
-----------------INCREMENTARE
drop sequence incrementare_editura;
create sequence incrementare_editura
start with 1000
increment by 1
minvalue 999
maxvalue 9999
nocycle;

drop sequence incrementare_carte;
create sequence incrementare_carte
start with 100000
increment by 1
minvalue 100000
maxvalue 999999
nocycle;

drop sequence incrementare_metoda_livrare;
create sequence incrementare_metoda_livrare
start with 1
increment by 1
minvalue 1
maxvalue 99999
nocycle;

select * from strada;
drop sequence incrementare_strada;
create sequence incrementare_strada
start with 11
increment by 1
minvalue 1
maxvalue 9999
nocycle;

create sequence incrementare_client
start with 1000
increment by 1
minvalue 1000
maxvalue 999999
nocycle;

drop sequence incrementare_detalii_comanda;
create sequence incrementare_detalii_comanda
start with 1
increment by 1
minvalue 1
maxvalue 99999
nocycle;

drop sequence incrementare_carte_comanda;
create sequence incrementare_carte_comanda
start with 1
increment by 1
minvalue 1
maxvalue 99999
nocycle;

drop sequence incrementare_adresa;
create sequence incrementare_adresa
start with 1
increment by 1
minvalue 1
maxvalue 99999
nocycle;

drop sequence incrementare_comanda;
create sequence incrementare_comanda
start with 1
increment by 1
minvalue 1
maxvalue 9999
nocycle;

create sequence incrementare_adresa_client
start with 1
increment by 1
minvalue 1
maxvalue 99999
nocycle;


-----------------INSERARI

select * from detalii_comanda;

insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1012,'CLB',6);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1004,'EAGS',8);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1001,'KK',5);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1018,'SD',7);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1001,'TS',10);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1013,'LAA',2);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1004,'HB',9);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1001,'KK',1);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1018,'CB',3);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1005,'BD',4);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1002,'LAA',11);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1018,'TS',3);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1005,'TS',4);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1001,'TS',5);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1018,'CB',7);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1004,'PW',8);
insert into detalii_comanda(cod_detalii_comanda,id_client,cod_librarie,cod_comanda) values (incrementare_detalii_comanda.nextval,1004,'TS',9);


select * from adresa_client;

insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,1,1000);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,3,1001);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,5,1002);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,7,1003);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,9,1004);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,2,1005);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,4,1006);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,6,1007);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,8,1008);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,10,1009);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,4,1010);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,6,1011);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,7,1012);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,1,1013);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,10,1014);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,8,1015);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,4,1016);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,7,1017);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,1,1018);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,3,1019);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,1,1020);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,7,1011);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,10,1002);
insert into adresa_client(cod_adresa_client,cod_adresa,id_client) values (incrementare_adresa_client.nextval,9,1008);


select * from carte_comanda;

insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100025,1);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100002,2);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100003,3);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100004,4);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100008,5);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100016,6);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100010,7);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100003,7);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100019,8);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100022,8);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100028,9);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100000,3);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100000,4);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100000,5);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100000,9);
insert into carte_comanda(cod_carte_comanda,cod_carte,cod_comanda) values (incrementare_carte_comanda.nextval,100000,10);


--update carte_comanda set cod_carte=100003 where cod_carte=100011;


select*from comanda;

insert into comanda(cod_comanda, pret_total, cod_adresa, cod_status, cod_livrare, data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,21,2, 3 ,2,'21/05/2024',null);
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,30,4, 5 ,4,'22/05/2024',null);
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,24,9, 6 ,5,'12/04/2024','17/04/2024');
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,25,5, 6 ,1,'02/03/2024','07/03/2024');
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,31,3, 6 ,3,'10/01/2024','16/01/2024');
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,20,1, 1 ,7,'25/05/2024',null);
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,26,6, 2 ,6,'21/05/2024',null);
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,38,8, 4 ,1,'30/04/2024',null);
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,28,7, 6 ,4,'01/02/2024','06/02/2024');
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,14,10, 6 ,2,'10/02/2024','15/02/2024');
-- exemplu pentru exceptie la ex7
insert into comanda(cod_comanda, pret_total,cod_adresa,cod_status,cod_livrare,data_plasare_comanda,finalizare_comanda) values
(incrementare_comanda.nextval,null,1, 1, 1,'13/07/2024',null);


select * from adresa;

insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '101');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '102');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '103');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '104');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '105');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '106');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '107');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '108');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '109');
insert into adresa(cod_adresa, cod_oras) values (incrementare_adresa.nextval, '110');


select * from oras;

insert all
into oras(cod_oras, nume_oras, cod_strada) values ('101', 'Galati', 3)
into oras(cod_oras, nume_oras, cod_strada) values ('102', 'Cluj', 6)
into oras(cod_oras, nume_oras, cod_strada) values ('103', 'Bucuresti', 9)
into oras(cod_oras, nume_oras, cod_strada) values ('104', 'Iasi', 4)
into oras(cod_oras, nume_oras, cod_strada) values ('105', 'Brasov', 8)
into oras(cod_oras, nume_oras, cod_strada) values ('106', 'Dolj', 2)
into oras(cod_oras, nume_oras, cod_strada) values ('107', 'Prahova', 5)
into oras(cod_oras, nume_oras, cod_strada) values ('108', 'Sibiu', 7)
into oras(cod_oras, nume_oras, cod_strada) values ('109', 'Arad', 1)
into oras(cod_oras, nume_oras, cod_strada) values ('110', 'Constanta', 10)
select * from dual;

select* from strada;

insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Bulevardul Brailei', 20);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Strada Domneasca', 15);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Strada Panselutei', 30);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Bulevardul Dunarea', 45);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Aleea Morilor', 5);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Strada Caraiman', 12);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Strada Alexandru Ioan Cuza', 7);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Strada Florilor', 18);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Aleea Mercur', 25);
insert into strada(cod_strada, nume_strada, numar_strada) values (incrementare_strada.nextval, 'Bulevardul Galati', 8);


select*from recenzie;

insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (1,1001, 100020, 'O carte fascinanta!', 9.5);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (2,1002, 100011, 'Interesanta si captivanta!', 8.7);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (3,1003, 100017, 'Mi-a placut mult aceasta carte.', 8.9);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (4,1001, 100003, 'Un must-read pentru oricine!', 9.8);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (5,1010, 100011, 'O poveste emotionanta.', 8.3);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (6,1006, 100010, 'Am fost captivata de fiecare pagina.', 9.1);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (7,1019, 100006, 'Destul de plictisioare.', 6.3);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (8,1008, 100007, 'A devenit cartea mea favorita', 8.6);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (9,1018, 100010, 'M-a surprins in mod placut.', 8.8);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (10,1010, 100009, 'Foarte draguta si amuzanta.', 9.2);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (11,1001, 100019, 'Nu este genul meu.', 4.0);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (12,1018, 100024, 'Mi-a placut modul in care este scrisa.', 8.5);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (13,1013, 100002, 'M-a impresionat profund.', 9.3);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (14,1002, 100002, 'Costa prea mult.', 5.5);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (15,1005, 100004, 'Aceasta autoare niciodata nu da gres.', 8.4);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (16,1011, 100005, 'Nu este deloc originala.', 3.0);
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (17,1015, 100001, 'Ritmul lent si finalul grabit ii scad din valoare.', 4.0);
-- exceptie too many rows
insert into recenzie (cod_recenzie,id_client, cod_carte, descriere, nota) values (18,1001, 100019, 'Am citit-o din nou si mi s-a schimbat parerea.', 9.0);


select*from client;

insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Popescu', 'Ion', 'popescu.ion@gmail.com', '0726571900', '01/01/2022');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Ionescu', 'Maria', 'ionescu.maria@gmail.com', '0711852276', '15/07/2023');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Stanescu', 'Andrei', 'stanescu.andrei@gmail.com', '0745562722', '30/04/2021');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Radulescu', 'Elena', 'radulescu.elena@gmail.com', '0782726519', '10/09/2022');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Dumitrescu', 'Alexandru', 'dumitrescu.alexandru@gmail.com', '0786450976', '05/03/2023');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Stoica', 'Cristina', 'stoica.cristina@gmail.com', '0745824567', '20/12/2020');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Gheorghe', 'Ana', 'gheorghe.ana@gmail.com', '0787584962', '08/06/2021');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Marin', 'Ionut', 'marin.ionut@gmail.com', '0746958425', '03/02/2020');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Georgescu', 'Laura', 'georgescu.laura@gmail.com', '0784559862', '14/11/2019');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Neacsu', 'Adrian', 'neacsu.adrian@gmail.com', '0714855266', '22/08/2020');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Mihai', 'Ioana', 'mihai.ioana@gmail.com', '0745484995', '17/05/2018');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Florescu', 'Dragos', 'florescu.dragos@gmail.com', '0728008564', '29/10/2019');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Luca', 'Daniela', 'luca.daniela@gmail.com', '0713584955', '02/04/2017');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Barbu', 'Bogdan', 'barbu.bogdan@gmail.com', '0777852651', '07/09/2018');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Manea', 'Gabriela', 'manea.gabriela@gmail.com', '0712458963', '18/03/2019');
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Ciobanu', 'Victor', 'ciobanu.victor@gmail.com', '0725836914', to_char(sysdate, 'DD/MM/YYYY'));
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Tudor', 'Elena', 'tudor.elena@gmail.com', '0711559862', to_char(sysdate, 'DD/MM/YYYY'));
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Puscas', 'Mircea', 'puscas.mircea@gmail.com', '0748095562', to_char(sysdate, 'DD/MM/YYYY'));
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Enescu', 'Mihaela', 'enescu.mihaela@gmail.com', '0700298566', to_char(sysdate, 'DD/MM/YYYY'));
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Iancu', 'Andreea', 'iancu.andreea@gmail.com', '0742659031', to_char(sysdate, 'DD/MM/YYYY'));
insert into client(id_client, nume_client, prenume_client, email_client, numar_telefon_client, data_inregistrare) 
values (incrementare_client.nextval, 'Barbu', 'Crina', 'barbu.crina@gmail.com', '0745657832', to_char(sysdate, 'DD/MM/YYYY'));



select * from metoda_livrare;

insert into metoda_livrare(cod_livrare, nume_livrare, firma_transport,cost_livrare) values (incrementare_metoda_livrare.nextval, 'aerian','FedEx',100);
insert into metoda_livrare(cod_livrare, nume_livrare, firma_transport,cost_livrare) values (incrementare_metoda_livrare.nextval, 'maritim','Maersk',60);
insert into metoda_livrare(cod_livrare, nume_livrare, firma_transport,cost_livrare) values (incrementare_metoda_livrare.nextval, 'aerian','DHL',85);
insert into metoda_livrare(cod_livrare, nume_livrare, firma_transport,cost_livrare) values (incrementare_metoda_livrare.nextval, 'terestru','DB Schenker',45);
insert into metoda_livrare(cod_livrare, nume_livrare, firma_transport,cost_livrare) values (incrementare_metoda_livrare.nextval, 'oceanic','CMA CGM',75);
insert into metoda_livrare(cod_livrare, nume_livrare, firma_transport,cost_livrare) values (incrementare_metoda_livrare.nextval, 'terestru','UPS',50);
insert into metoda_livrare(cod_livrare, nume_livrare, firma_transport,cost_livrare) values (incrementare_metoda_livrare.nextval, 'maritim','Kuehne + Nagel',60);


select * from status_comanda;

insert all
into status_comanda(cod_status, nume_status_comanda) values(1,'in curs de procesare')
into status_comanda(cod_status, nume_status_comanda) values(2,'procesata')
into status_comanda(cod_status, nume_status_comanda) values(3,'in curs de pregatire')
into status_comanda(cod_status, nume_status_comanda) values(4,'in depozit')
into status_comanda(cod_status, nume_status_comanda) values(5,'la curier')
into status_comanda(cod_status, nume_status_comanda) values(6,'finalizata')
select * from dual;


select * from gen;

insert all
into GEN(cod_gen, nume_gen, subgen) values (100,'horror','zombies')
into GEN(cod_gen, nume_gen, subgen) values (101,'comedy','romantic comedy')
into GEN(cod_gen, nume_gen, subgen) values (102,'drama','slice of life')
into GEN(cod_gen, nume_gen, subgen) values (103,'fantasy','mythic')
into GEN(cod_gen, nume_gen, subgen) values (104,'mystery','paranormal')
into GEN(cod_gen, nume_gen, subgen) values (105,'romance','holidays')
into GEN(cod_gen, nume_gen, subgen) values (106,'science fiction','aliens')
into GEN(cod_gen, nume_gen, subgen) values (107,'thriller','crimes')
into GEN(cod_gen, nume_gen, subgen) values (108,'adventure','survival')
into GEN(cod_gen, nume_gen, subgen) values (109,'history','time travel')
select * from dual;

select * from librarie;

insert all
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('SC','Shakespeare and Company','Paris','https://www.shakespeareandcompany.com/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('TS','The Strand','New York City','https://www.strandbooks.com/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('CLB','City Lights Books','San Francisco','https://citylights.com/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('EAGS','El Ateneo Grand Splendid','Buenos Aires',null)
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('LAA','Libreria Acqua Alta','Venice','https://www.libreriacqualta.it/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('PW','Powell?s','Portland','https://www.powells.com/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('SD','Selexyz Dominicanen','Maastricht',null)
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('AB','Atlantis Books','Oia','https://atlantisbooks.org/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('LL','Livraria Lello','Porto','https://www.livrarialello.pt/en/home')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('HB','Honesty Bookshop','Hay-on-Wye','https://theshopkeepers.com/shops/honesty-bookshop/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('KK','Kinokuniya','Sydney','https://www.kinokuniya.com/')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('BD','Boekhandel Dominicanen','Maastricht','https://libris.nl/dominicanen')
into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('CB','Cook and Book','Brussels','https://cookandbook.com/')
select*from dual;
insert into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('IN','Indigo','Pointe-Claire','https://www.indigo.ca/en-ca/');
insert into LIBRARIE(cod_librarie,nume_librarie,oras_librarie,website_librarie)
values ('MB','Munro´s Books','Victoria','https://www.munrobooks.com/');

rollback;
select * from autor;

insert all
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('CD','Dabos','Christelle','Razorbil')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('SK','King','Stephen','Scribner')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('WPB','Blatty','William Peter','Titan Books')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('SS','Smith','Scott','Harper Collins')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('EC','Chack','Erin','Titan Books')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('TH','Hibbert','Talia','Anchor')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('AHB','Blake','Ashley Herring','Canelo')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('KR','Kennedy','Ryan','Harper Paperbacks')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('MD','Dong','Maria','Grand Central Publishing')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('AB','Bartz','Andrea','Sourcebooks')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('HH','Hoang','Helen','Bloom Books')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('RC','Chupeco','Rin','Sourcebooks')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('GF','Flynn','Gillian','Scribner')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('LM','Morarity','Liane','Canelo')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('FH','Herbert','Frank','Titan Books')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('OSC','Card','Orson Scott','Anchor')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('WG','Gibson','William','Harper Paperbacks')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('DB','Brown','Dan','French and European Publications Inc')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('SL','Larron','Stieg','Sourcebooks')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('RLS','Stevenson','Robert Louis','Vintage')
into AUTOR(cod_autor, nume_autor, prenume_autor, nume_companie) values('CRZ','Zafon','Carlos Ruiz','Berkley')
select * from dual;


select * from editura;

insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Anchor', 'Berlin', to_date('10/01/2003', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Harper Paperbacks', 'London', to_date('03/04/2009', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Vintage', 'New York City', to_date('15/10/1997', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Razorbil', 'Instanbul', to_date('12/10/2010', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Berkley', 'Paris', to_date('01/08/2007', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Bloom Books', 'London', to_date('05/03/2015', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Grand Central Publishing', 'New York City', to_date('24/04/2010', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Sourcebooks', 'Chicago', to_date('07/09/2009', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'French and European Publications Inc', 'Paris', to_date('15/05/2004', 'DD/MM/YYYY'));
insert into editura (cod_editura, nume_editura, oras_editura, data_infiintare)
values (incrementare_editura.nextval, 'Scribner', 'Toronto', to_date('10/07/2008', 'DD/MM/YYYY'));



select*from carte;

select cod_carte, pret_carte from carte;
 
insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Salem`s Lot', 'SK', 1001, 100, 'TS', 672, 'engleza', to_date('24/09/2013', 'DD/MM/YYYY'), 14);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Exorcist', 'WPB', 1002, 100, 'EAGS', 400, 'engleza', to_date('04/10/2011', 'DD/MM/YYYY'), 13);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Ruins', 'SS', 1003, 100, 'LAA', 325, 'franceza', to_date('26/02/2008', 'DD/MM/YYYY'), 17);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'This Is Really Happening', 'EC', 1004, 101, 'CB', 234, 'engleza', to_date('01/01/2013', 'DD/MM/YYYY'), 10);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Act your age, Eve Brown', 'TH', 1001, 101, 'BD', 400, 'engleza', to_date('09/03/2021', 'DD/MM/YYYY'), 11);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Delilah Green Doesn`t Care', 'AHB', 1005, 101, 'TS', 400, 'engleza', to_date('22/02/2022', 'DD/MM/YYYY'), 12);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Long Shot', 'KR', 1006, 102, 'PW', 480, 'franceza', to_date('08/09/2023', 'DD/MM/YYYY'), 13);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Liar, Dreams, Thief', 'MD', 1007, 102, 'AB', 336, 'germana', to_date('10/01/2023', 'DD/MM/YYYY'), 26);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'We Were Never Here', 'AB', 1004, 102, 'KK', 352, 'engleza', to_date('05/07/2022', 'DD/MM/YYYY'), 17);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Merry Inkmas', 'TH', 1001, 105, 'EAGS', 190, 'franceza', to_date('10/03/2017', 'DD/MM/YYYY'), 15);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Kiss Quotient', 'HH', 1005, 105, 'SD', 352, 'engleza', to_date('01/01/2018', 'DD/MM/YYYY'), 16);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Get a life, Chloe Brown', 'TH', 1001, 105, 'SC', 384, 'engleza', to_date('05/11/2019', 'DD/MM/YYYY'), 10);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Bone Witch', 'RC', 1008, 103, 'CLB', 432, 'engleza', to_date('20/01/2015', 'DD/MM/YYYY'), 24);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Les Fiances de l`hiver', 'CD', 1009, 103, 'HB', 608, 'franceza', to_date('06/06/2013', 'DD/MM/YYYY'), 29);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Hazel Bly and Beep Blue Sea', 'AHB', 1005, 103, 'LL', 352, 'germana', to_date('25/05/2021', 'DD/MM/YYYY'), 18);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Mr Mercedes', 'SK', 1002, 104, 'KK', 659, 'franceza', to_date('10/03/2018', 'DD/MM/YYYY'), 22);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Gone Girl', 'GF', 1009, 104, 'CLB', 255, 'italiana', to_date('03/08/2011', 'DD/MM/YYYY'), 20);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Big Little Lies', 'LM', 1001, 104, 'CB', 301, 'engleza', to_date('12/05/2008', 'DD/MM/YYYY'), 13);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Dune', 'FH', 1007, 106, 'BD', 260, 'franceza', to_date('15/10/2015', 'DD/MM/YYYY'), 18);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Ender`s Game', 'OSC', 1004, 106, 'EAGS', 452, 'germana', to_date('20/01/2013', 'DD/MM/YYYY'), 23);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Neuromancer', 'WG', 1003, 106, 'LAA', 477, 'engleza', to_date('05/07/2002', 'DD/MM/YYYY'), 13);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Da Vinci Code', 'DB', 1009, 107, 'SD', 500, 'franceza', to_date('15/05/2011', 'DD/MM/YYYY'), 12);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Girl with the Dragon Tattoo', 'SL', 1005, 107, 'PW', 562, 'franceza', to_date('10/12/2020', 'DD/MM/YYYY'), 15);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Hound of the Baskervilles', 'SS', 1002, 107, 'HB', 440, 'franceza', to_date('16/02/2023', 'DD/MM/YYYY'), 28);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Call of the Wild', 'LM', 1001, 108, 'SC', 280, 'engleza', to_date('27/03/2012', 'DD/MM/YYYY'), 19);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Treasure Island', 'RLS', 1009, 108, 'KK', 180, 'germana', to_date('08/08/2018', 'DD/MM/YYYY'), 21);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Shadow of the Wind', 'CRZ', 1004, 108, 'AB', 522, 'italiana', to_date('01/10/2016', 'DD/MM/YYYY'), 20);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Guns, Germs and Steel', 'AHB', 1005, 109, 'AB', 237, 'engleza', to_date('30/03/2009', 'DD/MM/YYYY'), 18);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'Team of Rivals', 'DB', 1003, 109, 'HB', 345, 'franceza', to_date('09/04/2010', 'DD/MM/YYYY'), 14);

insert into carte (cod_carte, nume_carte, cod_autor, cod_editura, cod_gen, cod_librarie, numar_pagini, limba, data_publicare, pret_carte)
values (incrementare_carte.nextval, 'The Rise and Fall of the Third Reich', 'RC', 1009, 109, 'LL', 562, 'engleza', to_date('10/11/2013', 'DD/MM/YYYY'), 16);


rollback;

commit;
